-- Basement Stage 1 schema foundation. Media URLs point to object storage, never raw audio/video blobs.
create table public.profiles (id uuid primary key, username text unique not null, display_name text not null, avatar_url text, banner_url text, bio text, location text, role text not null default 'Artist', genres text[] default '{}', social_links jsonb default '[]', created_at timestamptz default now());
create table public.follows (follower_id uuid references profiles(id) on delete cascade, following_id uuid references profiles(id) on delete cascade, created_at timestamptz default now(), primary key (follower_id, following_id));
create table public.songs (id uuid primary key, user_id uuid references profiles(id) on delete cascade, title text not null, artist text not null, cover_art_url text, audio_url text, duration_seconds int, genre text, description text, tags text[] default '{}', created_at timestamptz default now());
create table public.posts (id uuid primary key, user_id uuid references profiles(id) on delete cascade, body text, content_type text not null check (content_type in ('text','music','triller','image','link')), media_url text, created_at timestamptz default now());
create table public.song_posts (post_id uuid references posts(id) on delete cascade, song_id uuid references songs(id) on delete cascade, primary key (post_id, song_id));
create table public.comments (id uuid primary key, post_id uuid references posts(id) on delete cascade, user_id uuid references profiles(id) on delete cascade, body text not null, created_at timestamptz default now());
create table public.reactions (id uuid primary key, post_id uuid references posts(id) on delete cascade, user_id uuid references profiles(id) on delete cascade, reaction_type text not null default 'like', created_at timestamptz default now(), unique(post_id,user_id,reaction_type));
create table public.reposts (id uuid primary key, post_id uuid references posts(id) on delete cascade, user_id uuid references profiles(id) on delete cascade, body text, created_at timestamptz default now(), unique(post_id,user_id));
create table public.feedback_submissions (id uuid primary key, song_id uuid references songs(id) on delete cascade, user_id uuid references profiles(id) on delete cascade, prompt text, start_second int not null, required_seconds int not null default 20, status text not null default 'queued', created_at timestamptz default now());
create table public.feedback_listens (id uuid primary key, submission_id uuid references feedback_submissions(id) on delete cascade, listener_id uuid references profiles(id) on delete cascade, listened_seconds numeric not null default 0, required_window_completed boolean default false, created_at timestamptz default now(), unique(submission_id, listener_id));
create table public.feedback_responses (id uuid primary key, submission_id uuid references feedback_submissions(id) on delete cascade, reviewer_id uuid references profiles(id) on delete cascade, body text, reaction text, created_at timestamptz default now(), unique(submission_id, reviewer_id));
create table public.feature_listings (id uuid primary key, user_id uuid references profiles(id) on delete cascade, title text not null, project text, description text, genre text, price_cents int, currency text default 'usd', is_paid boolean default false, availability text, created_at timestamptz default now());
create table public.beat_listings (id uuid primary key, user_id uuid references profiles(id) on delete cascade, song_id uuid references songs(id) on delete set null, title text not null, bpm int, musical_key text, genre text, tags text[] default '{}', price_cents int, currency text default 'usd', is_paid boolean default true, license_type text, description text, created_at timestamptz default now());
create table public.notifications (id uuid primary key, user_id uuid references profiles(id) on delete cascade, actor_id uuid references profiles(id) on delete set null, type text not null, entity_type text, entity_id uuid, read_at timestamptz, created_at timestamptz default now());
create index follows_following_idx on follows(following_id); create index posts_user_created_idx on posts(user_id, created_at desc); create index songs_user_created_idx on songs(user_id, created_at desc); create index feedback_queue_idx on feedback_submissions(status, created_at); create index notifications_user_created_idx on notifications(user_id, created_at desc);
