import { Heart, Link2, MessageCircle, Repeat2, Send, Sparkles, Video } from 'lucide-react';
import { getSong, getUser } from '@/lib/mock-data';
import type { Post, User } from '@/lib/types';
import { MusicPlayer } from './MusicPlayer';

export function Avatar({user}:{user:User}) { return <img src={user.avatar} alt={user.displayName} className="h-11 w-11 shrink-0 rounded-full object-cover ring-2 ring-[#494a42]"/>; }
export function FollowButton() { return <button className="shrink-0 border border-[#656850] px-3 py-1.5 text-xs font-bold uppercase tracking-wide text-neon transition hover:bg-neon hover:text-black">Follow</button>; }
export function PostComposer() { return <section className="surface border-l-2 border-l-neon p-4 sm:p-5" aria-label="Create a post"><p className="eyebrow mb-3 text-neon">Pin something to the wall</p><div className="flex gap-3"><Avatar user={getUser('u1')}/><button className="min-h-20 flex-1 border border-[#3a3b35] bg-[#0c0d0c] px-4 text-left text-sm leading-5 text-zinc-500 transition hover:border-[#656850]" aria-label="Write a post">What are you working on? Drop a snippet, link, or collab call.</button></div><div className="mt-4 flex items-center justify-between gap-3 border-t border-[#34352f] pt-3"><div className="flex min-w-0 flex-wrap gap-2"><button className="action-button"><Link2 size={16}/> <span>Attach song</span></button><button className="action-button"><Video size={16}/> <span>Triller clip</span></button></div><button className="accent-button min-h-11 shrink-0 px-5 text-sm font-black uppercase tracking-wide">Post</button></div></section>; }
const actionData = [[Heart, 'likes'], [MessageCircle, 'comments'], [Repeat2, 'reposts'], [Send, 'shares']] as const;
export function PostCard({post}:{post:Post}) { const user = getUser(post.userId), song = getSong(post.songId); return <article className="surface p-4 sm:p-5"><div className="flex gap-3"><Avatar user={user}/><div className="min-w-0 flex-1"><div className="flex min-w-0 items-start gap-2"><div className="min-w-0"><div className="flex min-w-0 items-center gap-1.5"><p className="truncate text-sm font-bold text-zinc-100">{user.displayName}</p>{user.verified && <Sparkles className="shrink-0 text-neon" size={15} aria-label="Verified"/>}</div><p className="truncate text-xs text-zinc-500">@{user.username} <span aria-hidden="true">·</span> {post.createdAt}</p></div><div className="ml-auto"><FollowButton/></div></div><p className="mt-3 whitespace-pre-line text-[15px] leading-6 text-zinc-200">{post.body}</p>{post.type === 'triller' && <div className="mt-4 aspect-video overflow-hidden border border-[#45413c] bg-[#23211e] p-4"><Video size={21} className="text-neon"/><div className="mt-auto flex h-[calc(100%-1.5rem)] flex-col justify-end"><p className="eyebrow text-neon">Triller clip</p><p className="mt-1 text-sm font-semibold text-zinc-100">Short-form music clip</p><p className="mt-0.5 text-xs text-zinc-400">Attached song below</p></div></div>}{song && <div className="mt-4"><MusicPlayer song={song}/></div>}<div className="mt-4 flex items-center justify-between border-t border-[#34352f] pt-3">{actionData.map(([Icon, label]) => <button key={label} className="flex items-center gap-1.5 px-1 py-1 text-xs text-zinc-500 transition hover:text-neon" aria-label={`${post.stats[label]} ${label}`}><Icon size={17}/><span>{post.stats[label]}</span></button>)}</div></div></div></article>; }
export function UserCard({user}:{user:User}) { return <div className="surface rounded-2xl p-4"><div className="flex items-center gap-3"><Avatar user={user}/><div className="min-w-0"><p className="truncate text-sm font-bold">{user.displayName}</p><p className="truncate text-xs text-zinc-500">@{user.username} · {user.role}</p></div><div className="ml-auto"><FollowButton/></div></div><p className="mt-3 text-sm leading-5 text-zinc-400">{user.bio}</p><div className="mt-3 flex flex-wrap gap-1.5">{user.genres.map(g => <span className="rounded-md bg-[#202126] px-2 py-1 text-[11px] text-zinc-400" key={g}>{g}</span>)}</div></div>; }
